### PR TITLE
Deprecate heroku orgs:default

### LINKED ISSUE #25: Add message to deprecate `heroku orgs:default`
https://github.com/heroku/heroku/blob/master/lib/heroku/command/orgs.rb#L50-L52

### PR DESCRIPTION
**Pull request by raulb**
Closes #25

cc @dickeyxxx

### CODE REVIEW

**Comment by jdx** [comment]
I'm confused. Why did you extend that other command instead of just making a new one?

**Comment by raulb** [comment]
Oh, because I thought that was the right thing to do since the command is
'Heroku orgs'.

Now that you mention it, it probably makes more sense not doing anything at
all and leave it in the ruby code.

I thought the ultimate goal was to get rid of all that in some point.

**Comment by raulb** [comment]
@dickeyxxx ready for review.

**Comment by jdx** [comment]
you'll have to do the unwrapping, but other than that lgtm

**Comment by raulb** [comment]
@dickeyxxx https://github.com/heroku/heroku-orgs/commit/0a9be4796964d478cb57af0f647211f5c1fa1a87

**Pull request merged**
