### PR TITLE
Join org apps using v3 endpoint instead

### PR DESCRIPTION
**Pull request by raulb**
See https://github.com/heroku/api/issues/6287 and https://github.com/heroku/api/pull/6655 for more context.

cc @dmcinnes @heroku/management-experience

### CODE REVIEW

**Comment by raulb** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7wr9vxm8&#x2F;414-update-the-heroku-orgs-cli-to-stop-using-post-v1-for-joining-an-application"> Update the Heroku Orgs CLI to stop using &#x60;POST v1&#x2F;...&#x60; for joining an application</a>

**Comment by dmcinnes** [comment]
Thanks! 👍

**Comment by raulb** [comment]
@dmcinnes i've got [this other PR](https://github.com/heroku/heroku-orgs/pull/62) in the works, so I'll probably cut a new release for this plugin once the other is completed, if that's ok. It should be before end of tomorrow.

**Comment by dmcinnes** [comment]
@raulb oh yeah, no rush!

**Pull request merged**
