### PR TITLE
Heroku-clize update

### PR DESCRIPTION
**Pull request by raulb**

### CODE REVIEW

**Comment by raulb** [comment]
@dickeyxxx @ransombriggs what's the easiest way to unit test the output of an error?

When updating privileges, I want to make sure I throw [this error](https://github.com/heroku/heroku-orgs/blob/heroku-clize-update/commands/access/update.js#L12) which I'm testing [here](https://github.com/heroku/heroku-orgs/blob/heroku-clize-update/test/commands/access/update.js#L50).

The only workaround I've found is [disabling](https://github.com/heroku/heroku-orgs/blob/heroku-clize-update/test/commands/access/update.js#L34) and [enabling](https://github.com/heroku/heroku-orgs/blob/heroku-clize-update/test/commands/access/update.js#L38) raising errors in those places, but that I don't think that's correct.

What should I do differently?

**Comment by ransombriggs** [comment]
@raulb It is kinda hacky, but this is how I did it (and should probably move this to heroku-cli-util)

https://github.com/heroku/heroku-apps/blob/master/lib/error.js
https://github.com/heroku/heroku-apps/blob/master/lib/buildpacks.js#L13
https://github.com/heroku/heroku-apps/blob/master/test/commands/buildpacks/add.js#L15
https://github.com/heroku/heroku-apps/blob/master/test/commands/buildpacks/add.js#L241
https://github.com/heroku/heroku-apps/blob/master/test/assert_exit.js#L6

**Comment by ransombriggs** [comment]
@raulb If you want to keep raising your error, you can also test it using using the technique I used here.  Where basically you test your error code in the `catch`, and have a failure in a `then` that is basically an `assert false`.

https://github.com/heroku/heroku-apps/blob/master/test/assert_exit.js#L8

**Comment by raulb** [comment]
@ransombriggs thanks for the tip!!!  :tophat: https://github.com/heroku/heroku-orgs/commit/e6105ca3a777ff93474b0fd7cd10338c207d6fa7

:+1: on making this part of the `heroku-cli-util`

**Pull request merged**
