### PR TITLE
Updates to permissions

### PR DESCRIPTION
**Pull request by michaelw99**
Now supports --permissions, --privileges is deprecated. Changes throughout code to use permissions instead of privileges.

### CODE REVIEW

**Comment by raulb** [comment]
@michaelw99 👍

**Comment by raulb** [comment]
@michaelw99 looks like this PR needs a rebase now.

**Comment by michaelw99** [comment]
@raulb Done 👍

**Comment by raulb** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;txTJpKcd&#x2F;253-release-latest-changes-in-heroku-orgs-cli"> Release latest changes in heroku-orgs CLI</a>

**Pull request merged**
