### PR TITLE
added apps:transfer

### PR DESCRIPTION
**Pull request by jdx**

### CODE REVIEW

**Comment by ransombriggs** [comment]
@dickeyxxx before this is merged, we need to implement the `--locked` flag for org transfers, see https://github.com/heroku/heroku/pull/1896

**Comment by raulb** [comment]
For the record. With this change we're deprecating the command `heroku sharing:transfer`:

```
$ heroku sharing:transfer ORG-NAME -a APP-NAME
 ▸    This command is now heroku apps:transfer
```

**Comment by raulb** [comment]
@ransombriggs https://github.com/heroku/heroku-orgs/commit/7ba5400d7035648c9589e8f50ba0dbdb485f609b

```
$ heroku apps:transfer organization-name-test -a sleepy-mesa-53642 --locked
Transferring sleepy-mesa-53642 to organization-name-test... done
Locking sleepy-mesa-53642... done
```

Though, not sure what's the best way to unit test that. Recommendations?

**Comment by ransombriggs** [comment]
@raul I added a unit test for the --locked flag on apps:transfer in cb67c916ee668740c4f474e895ef9808d7ed584e

**Comment by raulb** [comment]
@ransombriggs awesome!, thanks!

**Pull request merged**
