### PR TITLE
Overwrites old functionality

### PR DESCRIPTION
**Pull request by raulb**
Commands like these ones are still used in https://github.com/heroku/heroku/blob/master/lib/heroku/command/apps.rb#L274-L342:
- heroku join
- heroku lock
- heroku unlock
- heroku leave

This PR overwrites that without deprecating its use.

cc @heroku/management-experience @dickeyxxx

### CODE REVIEW

**Comment by jdx** [comment]
you need to mark all these as hidden topics otherwise you will see them under `heroku help`: https://github.com/heroku/heroku-apps/blob/master/index.js#L5

**Comment by raulb** [comment]
@dickeyxxx https://github.com/heroku/heroku-orgs/pull/36/commits/97d833eaa5d508eae419d481e2e8da1cfa38feb5

**Comment by raulb** [comment]
```
➼  heroku-orgs [rbarroso-ltm] { ovewrite-old-apps-commands } ✓ heroku plugins:link .
Symlinked heroku-orgs
➼  heroku-orgs [rbarroso-ltm] { ovewrite-old-apps-commands } ✓ heroku help | grep join
➼  heroku-orgs [rbarroso-ltm] { ovewrite-old-apps-commands } ✓
```

**Comment by jdx** [comment]
lgtm

**Comment by raulb** [comment]
@dickeyxxx fyi, just released this.

**Pull request merged**
