### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raulb**

### CODE REVIEW

**Comment by raulb** [comment]
@eablack mind reviewing?

You can see the new README in https://github.com/heroku/heroku-orgs/blob/updates-readme/README.md

**Comment by raulb** [comment]
One of the reasons is that I don't think it's useful to maintain a list of existing commands with their outputs. It gets pretty easy out of date.

**Comment by eablack** [comment]
Yeah, LGTM. Might be worth keeping the basic `heroku orgs` usage comment in the README?

**Comment by eablack** [comment]
👍

**Comment by raulb** [comment]
@eablack something like the following? 

```
$ heroku help command
```

I'm basically trying to avoid to have to keep that up to date.

**Pull request merged**
